title: DreamConsole Ⓒ 2019
logo: /assets/img/logo_dreamconsole_sq.jpg
description: Game developer's blog
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal


# Plugins
plugins: [jekyll-paginate]
